<?php

namespace Egret\Queue\Test;

use Egret\Queue\AbstractQueueCommand;
use Monolog\Handler\RotatingFileHandler;
use Monolog\Logger;

class TestRedisQueue extends AbstractQueueCommand
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('redis')->setDescription('测试redis队列');
        $this->driver = 'redis';
        // 以predis为驱动
        $this->config = include CONSOLE_PATH . '/test/config/redis.php';
//        $this->pidPath = CONSOLE_PATH . '/test/runtime';
    }

    protected function getLogger()
    {
        $logger = new Logger('queue');
        $rotating = new RotatingFileHandler(CONSOLE_PATH . '/test/runtime/info.log', 30);
        $logger->pushHandler($rotating);
        return $logger;
    }

    protected function getDingTalk()
    {
        return null;
    }
}