<?php


namespace Egret\Queue\Test;


use Egret\Queue\AbstractQueueCommand;

class TestKafkaQueue extends AbstractQueueCommand
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->driver = 'kafka';
        $this->setName('kafka')->setDescription('测试kafka队列');
        $this->config = include CONSOLE_PATH . '/test/config/kafka.php';
        $this->pidPath = CONSOLE_PATH . '/test/runtime';
    }

    protected function getLogger()
    {
        return null;
    }

    protected function getDingTalk()
    {
        return null;
    }
}