#!/usr/bin/env php
<?php

use Egret\Queue\Console;

set_time_limit(0);
date_default_timezone_set('PRC');

define('CONSOLE_PATH', __DIR__);

// autoload composer
foreach ([
             __DIR__ . '/../../../autoload.php',
             __DIR__ . '/../../autoload.php',
             __DIR__ . '/../../vendor/autoload.php',
             __DIR__ . '/../vendor/autoload.php',
             __DIR__ . '/vendor/autoload.php',
         ] as $value) {
    if (file_exists($value)) {
        define('COMPOSER_INSTALL', $value);
        break;
    }
}

if (!defined('COMPOSER_INSTALL')) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
}

include COMPOSER_INSTALL;

/**
 * This code
 *
 * __DIR__ . '/app'
 *
 * is test code.
 */
$path = [
    './app',
    './src',
    './application',
    './test',
    '../app',
    '../src',
    '../application',
    '../test',
    getcwd()
];

$class = [];
foreach ($path as $item) {
    if (file_exists($item . '/console.php')) {
        $data = include $item . '/console.php';
        if (is_array($data)) {
            $class = array_merge($class, $data);
        }
    }
}

$console = new Console($class);

$console->run();
